<template>
  <div>
    <ContentSection>
      <h1>4. ADD DESCRIPTIONS AND IMAGES TO PREFABS</h1>
      <p class="text-center mt-4 mb-4">
        Once you have added all the desired prefabs and moved the pivots, you need to add a description and an image to each child
        that contains MeshRenderer or SkinnedMeshRenderer, while the parent needs to be assigned a title.
      </p>
      <p class="text-center mt-4 mb-4">
        All this is done <u>automatically</u> by the asset (depending on the number of prefabs in
        the folder, it will take more or less time).
      </p>

      <div class="content mt-5">
        <div>
          <p>
            Just click on the button (at the top) <strong>Tools > Add Name and Descriptions To Prefab</strong>, 
            select the <u>prefab clone</u> folder, and a description, name, and image will be automatically
            assigned to each child and a title to the parent.
          </p>
        </div>
        <div>
          <div>
            <ImageZoomable src="/src/assets/images/Addname.png" alt="Add Name and Description" class="mb-3" />
          </div>
          <div>
            <ImageZoomable src="/src/assets/images/prefabcloneadd.png" alt="Prefab Clone Add" />
          </div>
        </div>
      </div>

      <div class="content mt-4">
        <div>
          <p>
            <strong class="text-danger">Do not insert anything inside the field</strong>
          </p>
          <ul>
            <li>1st image: child</li>
            <li>2nd image: parent</li>
          </ul>
        </div>
        <div>
          <ImageZoomable src="/src/assets/images/scriptabledescription.png" alt="Scriptable Description" class="mb-3" />
          <ImageZoomable src="/src/assets/images/scriptabletitle.png" alt="Scriptable Title" />
        </div>
      </div>

      <h3 class="text-center mt-5 mb-5">MANUAL TEXT INSERTION</h3>

      <div class="content mt-4">
        <div>
          <p>
            Double-click with the mouse on Piece Description or Preview Description to go directly to the corresponding 
            piece in the folder <code>Assets > AssemblyStation > ScriptableObjects</code>
          </p>
          <p>If you select Preview Description:</p>
        </div>
        <div>
          Child
          <ImageZoomable src="/src/assets/images/piecedescription.png" alt="Piece Description" class="mb-3" />
          Parent
          <ImageZoomable src="/src/assets/images/prewdescription.png" alt="Preview Description" />
        </div>
      </div>

      <div class="content mt-4">
        <div>
          <p>
            A window will open with all the scriptable objects created for each Prefab, here you can enter the name of the prefab and the description.
          </p>
        </div>
        <div>
          <ImageZoomable src="/src/assets/images/titlePrefab.png" alt="Title Prefab" class="mb-3" />
          <ImageZoomable src="/src/assets/images/previewasset.png" alt="Preview Asset" />
        </div>
      </div>

      <div class="content mt-4">
        <div>
          <p id="PieceDescriptionR">
            While if you select Piece Description, a window will open with all the scriptable objects
            created for each child of the prefab, here you can enter the name, description, image, and
            other things that we will see later.
          </p>
        </div>
        <div>
          <ImageZoomable src="/src/assets/images/pieces.png" alt="Pieces" class="mb-3" />
          <ImageZoomable src="/src/assets/images/pieceslist.png" alt="Pieces List" />
        </div>
      </div>

      <div class="content mt-4">
        <div>
          <p>
            This is what will be displayed in the game for the model Preview.
          </p>
        </div>
        <div>
          <ImageZoomable src="/src/assets/images/panelpreview.png" alt="Panel Preview" />
        </div>
      </div>

      <div class="content mt-4">
        <div>
          <p>
            This is what will be displayed in the game for the piece Preview.
          </p>
        </div>
        <div>
          <ImageZoomable src="/src/assets/images/piecespanel.png" alt="Pieces Panel" />
        </div>
      </div>

      <h3 class="text-center mt-5 mb-5">IMAGES</h3>

      <div class="content mt-4">
        <div>
          <p>
            Each "piece" will have an associated image that will be displayed in the preview.
          </p>
          <hr>
          <p>
            The image is generated automatically when we press the button <strong>Tools > Add Name and Descriptions To Prefab</strong>
          </p>
          <hr>
          <p>
            If you want to insert a personal image, just go to the Piece Description and
            select the desired image, replacing the one generated by the system.
          </p>
          <hr>
          <p>
            Functionality (Editor Mode): when clicking on Add Name and Descriptions To Prefab, a
            camera is generated in front of the piece and a photo is taken, this photo is saved in the
            folder <code>Assets > AssemblyStation > Screenshot > </code> and is associated with the child. For obvious
            reasons, the image may be compromised by the size of the piece and an incorrect angle. For this
            reason, it is recommended to insert a personal image if this problem occurs.
          </p>
        </div>
        <div>
          <ImageZoomable src="/src/assets/images/imagepiece.png" alt="Image Piece" class="mb-3" />
          <ImageZoomable src="/src/assets/images/imagepiecePanel.png" alt="Image Piece Panel" />
        </div>
      </div>
    </ContentSection>
  </div>
</template>

<script>
import ContentSection from '@/components/ContentSection.vue'
import ImageZoomable from '@/components/ImageZoomable.vue'

export default {
  name: 'Descriptions',
  components: {
    ContentSection,
    ImageZoomable
  }
}
</script>

<style scoped>
.content {
  display: flex;
  flex-direction: row;
  align-items: flex-start;
  gap: 20px;
  margin-top: 20px;
}

.content > div:first-child {
  flex: 1;
}

.content > div:last-child {
  flex: 1;
}

@media (max-width: 768px) {
  .content {
    flex-direction: column;
  }
}
</style>
